version: "3.7"
services:
  client1:
    container_name: client
    restart: always
    build: client
    ports:
    - 8080:8080
    links:
      - server12
  server12:
    container_name: server
    restart: always
    build: server
    ports:
    - 5000:5000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - 27017:27017